### ISSUE TITLE
Include Sockets and ProfileDirIO APIs directly in source

### ISSUE THREAD

**Issue by nhnt11** [mozilla/openwpm-firefox-webext#1]
I don't feel like maintaining two more repositories for those, let's just put the code in this repo directly

**Comment by nhnt11** [comment]
I thought of this as well and I think I agree that we should commit this into OpenWPM - there isn't really any scope for this to be reused elsewhere unless someone gets unusually creative.

**Comment by englehardt** [comment]
Done in #9 and #10
