### ISSUE TITLE
Ensure visit_id is being sent correctly to the platform

### ISSUE THREAD

**Issue by nhnt11** [mozilla/openwpm-firefox-webext#8]
Seems like `visit_id` is always `-1`, which is wrong. Need to investigate.

**Comment by englehardt** [comment]
This was caused by https://github.com/mozilla/OpenWPM/commit/57f635c7c74c26adb8b046d545769d8e638a1b7b. I've verified that visit_id is never set to `-1` in a test 10k site crawl that includes those fixes.
